const PROVIDERS = new Set(['binance', 'okx', 'bybit', 'bitget', 'gate']);
function providerKey(raw) { const v=String(raw||'').trim().toLowerCase().replaceAll('gate.io','gate'); if(v==='okex')return'okx'; return PROVIDERS.has(v)?v:null; }
function marketKey(raw) { const v=String(raw||'').toLowerCase(); return /contract|future|perpetual|swap|linear/.test(v)?'contract':'spot'; }
function compact(raw) { return String(raw||'').trim().toUpperCase().replace(/-SWAP$/i,'').replace(/_UMCBL$/i,'').replace(/[^A-Z0-9]/g,''); }
function split(symbol) { for(const q of ['USDT','USDC','USD']) if(symbol.endsWith(q)) return [symbol.slice(0,-q.length),q]; return [symbol,'USDT']; }
function okxId(symbol,market){const [b,q]=split(symbol);return `${b}-${q}${market==='contract'?'-SWAP':''}`;}
function gateId(symbol){const[b,q]=split(symbol);return `${b}_${q}`;}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function clamp(v,min,max,fallback){const n=Number.parseInt(String(v??''),10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function intervalMs(i){return ({'1m':60000,'3m':180000,'5m':300000,'15m':900000,'30m':1800000,'1h':3600000,'2h':7200000,'4h':14400000,'6h':21600000,'8h':28800000,'12h':43200000,'1d':86400000,'3d':259200000,'1w':604800000,'1M':2592000000})[i]||900000;}
function okxBar(i){return ({'1m':'1m','3m':'3m','5m':'5m','15m':'15m','30m':'30m','1h':'1H','2h':'2H','4h':'4H','6h':'6H','12h':'12H','1d':'1Dutc','3d':'3Dutc','1w':'1Wutc','1M':'1Mutc'})[i]||'15m';}
function gateBar(i){return ({'1m':'1m','5m':'5m','15m':'15m','30m':'30m','1h':'1h','2h':'2h','4h':'4h','6h':'6h','8h':'8h','12h':'12h','1d':'1d','3d':'3d','1w':'7d'})[i]||'15m';}
function bitgetBar(i){return ({'1m':'1m','3m':'3m','5m':'5m','15m':'15m','30m':'30m','1h':'1H','2h':'2H','4h':'4H','6h':'6H','12h':'12H','1d':'1D','3d':'3D','1w':'1W','1M':'1M'})[i]||'15m';}
function bybitBar(i){return ({'1m':'1','3m':'3','5m':'5','15m':'15','30m':'30','1h':'60','2h':'120','4h':'240','6h':'360','12h':'720','1d':'D','1w':'W','1M':'M'})[i]||'15';}
async function jsonFetch(urls,timeout=15000){const list=Array.isArray(urls)?urls:[urls];let last;for(const url of list){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{signal:controller.signal,headers:{accept:'application/json','user-agent':'KakaWeb3-Market-Worker/513.0'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json();}catch(e){last=e;}finally{clearTimeout(timer);}}throw last||new Error('upstream unavailable');}
function send(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});res.end(JSON.stringify(body));}
function marketRow(provider,market,symbol,base,quote,raw){return{provider,market_type:market,symbol:compact(symbol),raw_symbol:raw,base_asset:String(base).toUpperCase(),quote_asset:String(quote).toUpperCase(),status:'TRADING',active:true,source:`${provider}_official_public_market_render`};}

async function universe(provider,market){let rows=[];
 if(provider==='binance'){const p=await jsonFetch(market==='contract'?'https://fapi.binance.com/fapi/v1/exchangeInfo':['https://api.binance.com/api/v3/exchangeInfo','https://data-api.binance.vision/api/v3/exchangeInfo']);for(const x of(p.symbols||[])){if(String(x.status).toUpperCase()!=='TRADING')continue;if(market==='contract'&&String(x.contractType).toUpperCase()!=='PERPETUAL')continue;rows.push(marketRow(provider,market,x.symbol,x.baseAsset,x.quoteAsset,x.symbol));}}
 else if(provider==='okx'){const p=await jsonFetch(`https://www.okx.com/api/v5/public/instruments?instType=${market==='contract'?'SWAP':'SPOT'}`);for(const x of(p.data||[])){if(x.state&&x.state!=='live')continue;if(market==='contract'&&x.ctType!=='linear')continue;const b=x.baseCcy||x.ctValCcy,q=x.quoteCcy||x.settleCcy;if(b&&q)rows.push(marketRow(provider,market,x.instId,b,q,x.instId));}}
 else if(provider==='gate'){if(market==='contract'){const p=await jsonFetch(['https://api.gateio.ws/api/v4/futures/usdt/contracts','https://fx-api.gateio.ws/api/v4/futures/usdt/contracts']);for(const x of p||[]){if(x.in_delisting===true)continue;const [b,q='USDT']=String(x.name||'').toUpperCase().split('_');if(b)rows.push(marketRow(provider,market,x.name,b,q,x.name));}}else{const p=await jsonFetch('https://api.gateio.ws/api/v4/spot/currency_pairs');for(const x of p||[]){if(String(x.trade_status||'tradable').toLowerCase()!=='tradable')continue;const [b,q]=String(x.id||'').toUpperCase().split('_');if(b&&q)rows.push(marketRow(provider,market,x.id,x.base||b,x.quote||q,x.id));}}}
 else if(provider==='bitget'){const p=await jsonFetch(market==='contract'?'https://api.bitget.com/api/v2/mix/market/contracts?productType=USDT-FUTURES':'https://api.bitget.com/api/v2/spot/public/symbols');for(const x of(p.data||[])){const st=String(x.symbolStatus||x.status||'').toLowerCase();if(st&&!['normal','online','listed'].includes(st))continue;if(x.baseCoin&&x.quoteCoin)rows.push(marketRow(provider,market,x.symbol,x.baseCoin,x.quoteCoin,x.symbol));}}
 else {const category=market==='contract'?'linear':'spot';let cursor='';do{const suffix=market==='contract'?`&limit=1000${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`:'';const p=await jsonFetch(`https://api.bybit.com/v5/market/instruments-info?category=${category}${suffix}`);const result=p.result||{};for(const x of(result.list||[])){if(String(x.status||'Trading').toLowerCase()!=='trading')continue;if(market==='contract'&&String(x.contractType||'').toLowerCase()!=='linearperpetual')continue;const raw=String(x.symbol||'').toUpperCase(),[b,q]=split(raw);if(b&&q)rows.push(marketRow(provider,market,raw,x.baseCoin||b,x.quoteCoin||q,raw));}cursor=market==='contract'?String(result.nextPageCursor||''):'';}while(cursor);}
 return [...new Map(rows.map(x=>[`${x.provider}:${x.symbol}`,x])).values()].sort((a,b)=>a.symbol.localeCompare(b.symbol));
}
function tickerRow(provider,market,x,sym){const symbol=compact(sym);if(!symbol)return null;const last=num(x.last_price??x.lastPrice??x.last??x.close??x.lastPr),open=num(x.open_24h??x.openPrice??x.open??x.open24h??x.prevPrice24h);let pct=num(x.price_change_percent_24h??x.priceChangePercent??x.change_percentage??x.change24h??x.price24hPcnt);if(pct!==null&&(provider==='bitget'||provider==='bybit')&&Math.abs(pct)<=2)pct*=100;if(pct===null&&last!==null&&open)pct=(last-open)/open*100;return{provider,market_type:market,symbol,last_price:last,price:last,price_change_percent_24h:pct,quote_volume_24h:num(x.quote_volume_24h??x.quoteVolume??x.quote_volume??x.volume_24h_quote??x.volCcy24h??x.amount??x.quoteVolume24h??x.usdtVolume??x.turnover24h),base_volume_24h:num(x.base_volume_24h??x.volume??x.volume_24h??x.vol24h??x.baseVolume??x.base_volume??x.baseVolume24h??x.volume24h),high_24h:num(x.high_24h??x.highPrice??x.high24h??x.highPrice24h),low_24h:num(x.low_24h??x.lowPrice??x.low24h??x.lowPrice24h),funding_rate:num(x.fundingRate),open_interest:num(x.openInterest),open_interest_value:num(x.openInterestValue),source:`${provider}_official_public_ticker_render`,cached_at:new Date().toISOString()};}
async function tickers(provider,market){let items=[];if(provider==='binance'){const p=await jsonFetch(market==='contract'?'https://fapi.binance.com/fapi/v1/ticker/24hr':['https://api.binance.com/api/v3/ticker/24hr','https://data-api.binance.vision/api/v3/ticker/24hr']);items=Array.isArray(p)?p:[];}else if(provider==='okx'){const p=await jsonFetch(`https://www.okx.com/api/v5/market/tickers?instType=${market==='contract'?'SWAP':'SPOT'}`);items=p.data||[];}else if(provider==='gate'){const p=await jsonFetch(market==='contract'?['https://api.gateio.ws/api/v4/futures/usdt/tickers','https://fx-api.gateio.ws/api/v4/futures/usdt/tickers']:'https://api.gateio.ws/api/v4/spot/tickers');items=Array.isArray(p)?p:[];}else if(provider==='bitget'){const p=await jsonFetch(market==='contract'?'https://api.bitget.com/api/v2/mix/market/tickers?productType=USDT-FUTURES':'https://api.bitget.com/api/v2/spot/market/tickers');items=p.data||[];}else{const p=await jsonFetch(`https://api.bybit.com/v5/market/tickers?category=${market==='contract'?'linear':'spot'}`);items=p.result?.list||[];}return items.map(x=>tickerRow(provider,market,x,x.symbol??x.instId??x.contract??x.currency_pair)).filter(Boolean);}
function krow(provider,market,symbol,interval,a){const ts=num(a[0]),o=num(a[1]),h=num(a[2]),l=num(a[3]),c=num(a[4]);if([ts,o,h,l,c].some(v=>v===null))return null;return{provider,market_type:market,symbol,interval,open_time:new Date(ts).toISOString(),open_time_ms:ts,close_time:new Date(ts+intervalMs(interval)-1).toISOString(),open:o,high:h,low:l,close:c,volume:num(a[5])||0,quote_volume:num(a[6])||0,trade_count:num(a[7])||0,source:`${provider}_official_public_kline_render`};}
async function klines(provider,market,symbol,interval,end,limit){let rows=[];
 if(provider==='binance'){const base=market==='contract'?'https://fapi.binance.com/fapi/v1/klines':'https://api.binance.com/api/v3/klines';const p=await jsonFetch(`${base}?symbol=${symbol}&interval=${encodeURIComponent(interval)}&endTime=${end}&limit=${Math.min(1500,limit)}`);rows=(p||[]).map(a=>krow(provider,market,symbol,interval,[a[0],a[1],a[2],a[3],a[4],a[5],a[7],a[8]])).filter(Boolean);}
 else if(provider==='okx'){let after=end+1;while(rows.length<limit){const n=Math.min(300,limit-rows.length);const p=await jsonFetch(`https://www.okx.com/api/v5/market/history-candles?instId=${encodeURIComponent(okxId(symbol,market))}&bar=${encodeURIComponent(okxBar(interval))}&after=${after}&limit=${n}`);const data=p.data||[];if(!data.length)break;let oldest=after;for(const a of data){const r=krow(provider,market,symbol,interval,[a[0],a[1],a[2],a[3],a[4],a[5],a[7],0]);if(r){rows.push(r);oldest=Math.min(oldest,Number(a[0]));}}if(data.length<n||oldest>=after)break;after=oldest;}}
 else if(provider==='gate'){const sec=Math.max(60,Math.floor(intervalMs(interval)/1000)),to=Math.floor(end/1000),from=Math.max(0,to-(limit+5)*sec);const u=market==='contract'?`https://api.gateio.ws/api/v4/futures/usdt/candlesticks?contract=${encodeURIComponent(gateId(symbol))}&interval=${encodeURIComponent(gateBar(interval))}&from=${from}&to=${to}&limit=${Math.min(2000,limit)}`:`https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=${encodeURIComponent(gateId(symbol))}&interval=${encodeURIComponent(gateBar(interval))}&from=${from}&to=${to}&limit=${Math.min(1000,limit)}`;const p=await jsonFetch(u);rows=(p||[]).map(a=>Array.isArray(a)?krow(provider,market,symbol,interval,[Number(a[0])*1000,a[5],a[3],a[4],a[2],a[6],a[1],0]):krow(provider,market,symbol,interval,[Number(a.t)*1000,a.o,a.h,a.l,a.c,a.v,a.a??a.sum,a.n])).filter(Boolean);}
 else if(provider==='bitget'){const base=market==='contract'?'https://api.bitget.com/api/v2/mix/market/candles':'https://api.bitget.com/api/v2/spot/market/candles';const product=market==='contract'?'&productType=USDT-FUTURES':'';const p=await jsonFetch(`${base}?symbol=${symbol}${product}&granularity=${encodeURIComponent(bitgetBar(interval))}&endTime=${end}&limit=${Math.min(1000,limit)}`);rows=(p.data||[]).map(a=>krow(provider,market,symbol,interval,[a[0],a[1],a[2],a[3],a[4],a[5],a[6],0])).filter(Boolean);}
 else {const p=await jsonFetch(`https://api.bybit.com/v5/market/kline?category=${market==='contract'?'linear':'spot'}&symbol=${symbol}&interval=${encodeURIComponent(bybitBar(interval))}&end=${end}&limit=${Math.min(1000,limit)}`);rows=(p.result?.list||[]).map(a=>krow(provider,market,symbol,interval,[a[0],a[1],a[2],a[3],a[4],a[5],a[6],0])).filter(Boolean);}
 return [...new Map(rows.map(x=>[x.open_time_ms,x])).values()].sort((a,b)=>a.open_time_ms-b.open_time_ms).slice(-limit);
}

export async function handleMarketApi(req,res,url){
 if(!url.pathname.startsWith('/api/')) return false;
 if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET, OPTIONS','access-control-allow-headers':'content-type'});res.end();return true;}
 if(req.method!=='GET'){send(res,405,{ok:false,error:'GET required',rows:[]});return true;}
 try{
  const provider=providerKey(url.searchParams.get('provider')),market=marketKey(url.searchParams.get('market_type')||url.searchParams.get('market'));
  if(!provider){send(res,400,{ok:false,error:'unsupported provider',rows:[]});return true;}
  if(url.pathname==='/api/universe'){const quote=(url.searchParams.get('quote')||'USDT').toUpperCase(),query=(url.searchParams.get('query')||'').toUpperCase(),limit=clamp(url.searchParams.get('limit'),20,1000,120),cursor=clamp(url.searchParams.get('cursor'),0,10000000,0);const all=(await universe(provider,market)).filter(x=>x.quote_asset===quote&&(!query||x.symbol.includes(query)||x.base_asset.includes(query)));const rows=all.slice(cursor,cursor+limit),next=cursor+rows.length;send(res,200,{ok:true,provider,market_type:market,rows,total:all.length,next_cursor:next<all.length?String(next):'',has_more:next<all.length,provider_status:'official_public_ok_render',source:`${provider}_official_public_market_render`,cached_at:new Date().toISOString()});return true;}
  if(url.pathname==='/api/tickers'){const wanted=new Set(String(url.searchParams.get('symbols')||'').split(',').map(compact).filter(Boolean));const all=await tickers(provider,market),rows=wanted.size?all.filter(x=>wanted.has(x.symbol)):all.slice(0,120);send(res,200,{ok:true,provider,market_type:market,rows,source:`${provider}_official_public_ticker_render`,cached_at:new Date().toISOString()});return true;}
  if(url.pathname==='/api/klines'){const symbol=compact(url.searchParams.get('symbol')),interval=url.searchParams.get('interval')||'15m',end=clamp(url.searchParams.get('end_time'),1,Number.MAX_SAFE_INTEGER,Date.now()),limit=clamp(url.searchParams.get('limit'),20,1000,1000);if(!symbol){send(res,400,{ok:false,error:'symbol required'});return true;}const rows=await klines(provider,market,symbol,interval,end,limit);send(res,200,{ok:true,provider,market_type:market,symbol,interval,rows,source:`${provider}_official_public_kline_render`,cached_at:new Date().toISOString()});return true;}
  send(res,404,{ok:false,error:'unknown market api'});return true;
 }catch(error){send(res,502,{ok:false,error:String(error),rows:[],cached_at:new Date().toISOString()});return true;}
}
